apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-bzh3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yigu-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-bzh3@sha256:6bfe4e3836661d80fa84c3ec9e943f8eadce5e6c6fc38ef1bcb03f96f45ffeaf
        name: my-python
        resources: {}
status: {}
